### ISSUE TITLE
Messages don't display?

### ISSUE THREAD

**Issue by sdellis** [andyleach/vue-flash#14]
I'm attempting to use the vue-flash component via npm. I have it registered as a global component in my main.js file and can verify that via `console.log(Vue.options.components)`. I can also see the event firing in the Vue DevTools (but can't see the component there). My problem is that I don't see any flash message visually in my app. 

I have not used globally registered components before, so perhaps I'm missing something obvious?

Here's my test repo for proof (see main.js and HelloWorld component):
https://github.com/sdellis/vue-flash-test

**Comment by andyleach** [comment]
You aren't actually using the component anywhere that I could tell.  Drop in the snippet below into your App.vue file and it'll work

```html
<flash :timeout="10000" :display-icons="true" transition="fade"></flash>
```
