### ISSUE TITLE
.alert-wrap div remains invisible on screen, preventing mouse clicks

### ISSUE THREAD

**Issue by sdellis** [andyleach/vue-flash#16]
I love vue-flash, but I think that the `.alert-wrap` class should be hidden when the flash message disappears. Currently, it stays invisible on the screen, preventing the user from being able to click anything underneath it on the page.

Here's the lines of the class I'm referring to:
https://github.com/andyleach/vue-flash/blob/a01728c21d6a6c3d4c0f74da5fca125f5d2a46f0/src/Flash.vue#L110-L115

**Comment by andyleach** [comment]
Thanks for the heads up, I'll try and knock this out sometime this week.

**Comment by andyleach** [comment]
Addressed in #17
