### ISSUE TITLE
Node Compile Error - Do not use v-for index as key on <transition-group> children, this is the same as not using keys.

### ISSUE THREAD

**Issue by Jason-C-Fry** [andyleach/vue-flash#21]
`ERROR in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-40d2a988","hasScoped":true,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./node_modules/vue-flash/src/Flash.vue
(Emitted value instead of an instance of Error) 
  Error compiling template:
  
  <div class="alert-wrap" v-if="notifications.length > 0">
      <transition-group :name="transition" tag="div">
          <div :class="item.typeObject" role="alert" :key="index" v-for="(item, index) in notifications">
              <span v-if="displayIcons" :class="item.iconObject"></span> <span v-html="item.message"></span>
          </div>
      </transition-group>
  </div>
  
  - Do not use v-for index as key on <transition-group> children, this is the same as not using keys.

 @ ./node_modules/vue-flash/src/Flash.vue 10:23-222
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/less/app.less ./resources/assets/rebrand-styles/less/index.less`

The weird quick fix is to add +0 to the index for the v-for. I'm sure there's a more elegant way of fixing this.

**Comment by Jason-C-Fry** [comment]
Relevant info: https://github.com/vuejs/eslint-plugin-vue/issues/726

**Comment by andyleach** [comment]
Resolved in #22
